export type ProductPageData = {
  name: string
  eyebrow: string
  short: string
  headline: string
  sub: string
  capabilities: { t: string; d: string }[]
  spotlight: { headline: string; body: string; bullets: string[] }
  agent: { name: string; line: string }
  related: string[]
}

export const productPages: Record<string, ProductPageData> = {
  payments: { name: "Payments", eyebrow: "Move money", short: "Pay in and out, 60+ markets", headline: "Move money to 60+ markets in one click.", sub: "Collect and disburse from one platform, with accounts payable built in. Every transfer is routed across rails and 60+ markets for the best speed and cost, automatically.", capabilities: [{ t: "Pay-in and pay-out", d: "Collect and disburse from one platform, on the rail that fits each market." }, { t: "Accounts payable", d: "Bills parsed, approvals routed and pay runs scheduled for you." }, { t: "60+ markets", d: "Reach payees across currencies and rails without leaving Hinstantt." }], spotlight: { headline: "One platform for money in and out.", body: "Collect and disburse across rails and markets, with accounts payable built in.", bullets: ["Pay-in and pay-out from one place", "Bills parsed, approved and scheduled", "Reach 60+ markets on the right rail"] }, agent: { name: "Payments agent", line: "Routes every payment to the cheapest, fastest rail, automatically." }, related: ["accounts", "treasury", "invoicing-billing"] },
  "corporate-cards": { name: "Corporate Cards", eyebrow: "Spend", short: "Virtual and physical issuance", headline: "Issue a card in seconds, keep every limit.", sub: "Issue virtual and physical cards in seconds. Limits, policies, and freezes are enforced the moment a card is used, not after the fact.", capabilities: [{ t: "Virtual and physical", d: "Issue either in seconds and freeze any card instantly." }, { t: "Controls at authorization", d: "Per-card limits, categories and policies enforced at the swipe." }, { t: "Real-time visibility", d: "Every transaction coded and visible the moment it happens." }], spotlight: { headline: "Controls at the swipe, not the statement.", body: "Limits, policies and freezes are enforced the moment a card is used, so spend stays in bounds.", bullets: ["Issue virtual and physical cards in seconds", "Per-card limits, categories and freezes", "Transactions coded and visible in real time"] }, agent: { name: "Policy agent", line: "Reads every transaction against your rules and enforces them at authorization." }, related: ["expense", "payments", "accounting"] },
  expense: { name: "Expense", eyebrow: "Spend", short: "Submit to reimbursement", headline: "Expenses that file themselves.", sub: "From the receipt captured to the money reimbursed, the whole loop runs itself. Policy is checked on submission and entries are coded automatically.", capabilities: [{ t: "Receipt capture", d: "Snap or forward a receipt and let AI handle the rest." }, { t: "Policy at submission", d: "Out-of-policy spend is flagged before it is approved." }, { t: "Fast reimbursement", d: "Approved expenses are reimbursed without the back-and-forth." }], spotlight: { headline: "From receipt to reimbursed.", body: "Capture the receipt and the rest is automatic: coded, checked and reimbursed.", bullets: ["Snap or forward receipts from anywhere", "Policy checked at submission, not after", "Approved expenses reimbursed on schedule"] }, agent: { name: "Expense agent", line: "Codes receipts and checks them against policy on submission." }, related: ["corporate-cards", "travel", "accounting"] },
  travel: { name: "Travel", eyebrow: "Spend", short: "Book and track travel", headline: "Book travel that always stays in policy.", sub: "Request, approve, book, and track every trip in one flow. It is wired straight into Expense and Payments, so travel spend never falls through the cracks.", capabilities: [{ t: "Request and approve", d: "Trips approved against policy before anything is booked." }, { t: "Book and track", d: "Flights and stays booked and tracked in one itinerary view." }, { t: "Wired to spend", d: "Connected to Expense and Payments from end to end." }], spotlight: { headline: "Travel that books itself into the books.", body: "Trips are approved, booked and tracked, then flow straight into expense and payment.", bullets: ["Policy-checked before booking", "Flights and stays in one itinerary view", "Connected to Expense and Payments end to end"] }, agent: { name: "Travel agent", line: "Keeps every trip inside policy and in sync with spend." }, related: ["expense", "corporate-cards", "payments"] },
  accounts: { name: "Accounts", eyebrow: "Move money", short: "Multi-currency business accounts", headline: "One account for every currency you hold.", sub: "Hold USD, EUR, GBP, and more under a single verified business identity. Send and receive on 6+ payment rails from the same account.", capabilities: [{ t: "Multi-currency", d: "Hold USD, EUR, GBP and more in a single place." }, { t: "One business identity", d: "Every currency sits under one verified entity." }, { t: "6+ payment rails", d: "Send and receive on the rail that fits each market." }], spotlight: { headline: "One identity, every currency.", body: "Open multi-currency accounts under a single verified business identity, ready to move money on day one.", bullets: ["Hold USD, EUR, GBP and more", "Support for 6+ payment rails", "Local details where your customers and suppliers are"] }, agent: { name: "Accounts agent", line: "Routes each payment to the right rail for the destination." }, related: ["payments", "treasury", "stablecoin-ramp"] },
  treasury: { name: "Treasury", eyebrow: "Move money", short: "Cash management and yield", headline: "Always know where your cash sits, and put it to work.", sub: "See every balance across banks and currencies in one position. AI forecasts your cash, and yield-bearing accounts put idle balances to work.", capabilities: [{ t: "Multi-bank view", d: "Every bank and balance, in one position." }, { t: "AI cash forecasting", d: "See where your cash is heading before it gets there." }, { t: "Yield-bearing accounts", d: "Put idle balances to work without locking them up." }], spotlight: { headline: "Cash, working as hard as you do.", body: "See every balance across banks and currencies, and let idle cash earn while staying available.", bullets: ["One position across every bank and currency", "AI forecasts your runway and shortfalls", "Yield on balances you are not using"] }, agent: { name: "Treasury agent", line: "Forecasts your cash position and flags shortfalls daily." }, related: ["accounts", "payments", "reporting"] },
  "stablecoin-ramp": { name: "Stablecoin Ramp", eyebrow: "Move money", short: "Fiat and stablecoin, on and off", headline: "Cross between dollars and stablecoins instantly.", sub: "Move between fiat and stablecoin in a tap. Hold, send, and convert USDC and EURC as a first-class account type, right alongside your other balances.", capabilities: [{ t: "On and off ramp", d: "Move between fiat and stablecoin in a tap." }, { t: "Hold and convert", d: "USDC and EURC treated like any other balance." }, { t: "Send anywhere", d: "Move stablecoin to any wallet or counterparty." }], spotlight: { headline: "Fiat and stablecoin, one account.", body: "Move between dollars and stablecoins in a tap, and treat USDC and EURC like any other balance.", bullets: ["On and off ramp between fiat and stablecoin", "Hold, send and convert USDC and EURC", "Move to any wallet or counterparty"] }, agent: { name: "Ramp agent", line: "Converts at the best available rate when you move funds." }, related: ["accounts", "payments", "treasury"] },
  accounting: { name: "Accounting", eyebrow: "Operate", short: "AI ledger, auto statements", headline: "Close the books while the team sleeps.", sub: "An AI-classified general ledger that syncs to your ERP in real time. Your Balance Sheet, P&L, Cash Flow, and Trial Balance generate themselves, ready to review.", capabilities: [{ t: "AI-classified ledger", d: "Every transaction categorized and coded to the right account." }, { t: "Real-time ERP sync", d: "Two-way sync with NetSuite, QuickBooks, Xero and Sage." }, { t: "Statements on demand", d: "Balance Sheet, P&L, Cash Flow and Trial Balance, ready to review." }], spotlight: { headline: "Month-end, minus the month-end.", body: "Transactions sync as they happen and post to the right accounts, so closing is a review, not a scramble.", bullets: ["Two-way ERP sync with the tools you use", "Statements generated automatically", "Variance explained and accruals drafted for you"] }, agent: { name: "Close agent", line: "Reconciles accounts and drafts statements before the period ends." }, related: ["reporting", "payments", "treasury"] },
  procurement: { name: "Procurement", eyebrow: "Operate", short: "Request to three-way match", headline: "Every purchase, requested, approved and matched.", sub: "Request, approve, raise the purchase order, receive, and three-way match, all in one flow. Spend is controlled before it happens, not questioned after.", capabilities: [{ t: "Requests and approvals", d: "Route every request through the right approvers by policy." }, { t: "Purchase orders", d: "Issue and track POs against budgets in one place." }, { t: "Three-way match", d: "PO, receipt and invoice matched before anything is paid." }], spotlight: { headline: "Control spend before it happens.", body: "Every request runs through policy and budget before a purchase order is ever raised.", bullets: ["Approval routes by amount, team and vendor", "Purchase orders tracked against budget", "Three-way match across PO, receipt and invoice"] }, agent: { name: "Procurement agent", line: "Runs the three-way match and flags any mismatch." }, related: ["payments", "invoicing-billing", "expense"] },
  "invoicing-billing": { name: "Invoicing & Billing", eyebrow: "Operate", short: "Invoices, billing, collection", headline: "Get paid faster, on autopilot.", sub: "Create invoices and payment links, run recurring billing, and collect what you are owed. Payments reconcile themselves, so revenue lands without the chasing.", capabilities: [{ t: "Invoices and links", d: "Create invoices and shareable payment links in seconds." }, { t: "Recurring billing", d: "Subscriptions and schedules handled for you." }, { t: "Auto reconciliation", d: "Payments matched to invoices automatically." }], spotlight: { headline: "Revenue without the chasing.", body: "Send invoices and payment links, run recurring billing, and let reconciliation happen on its own.", bullets: ["Invoices and shareable payment links", "Recurring and scheduled billing", "Payments auto-matched to invoices"] }, agent: { name: "Billing agent", line: "Chases unpaid invoices and reconciles payments as they arrive." }, related: ["payments", "accounting", "reporting"] },
  reporting: { name: "Reporting", eyebrow: "Intelligence", short: "Spend and revenue insights", headline: "See the whole business in real time.", sub: "Spend reporting, revenue intelligence, and customer-health analytics in one place. AI surfaces what changed and why, before you go looking.", capabilities: [{ t: "Spend reporting", d: "Slice spend by team, vendor, category or entity." }, { t: "Revenue intelligence", d: "Track revenue, MRR and what is moving the numbers." }, { t: "Customer health", d: "Spot churn risk and expansion early." }], spotlight: { headline: "The numbers, explained.", body: "Reporting does not just show the data, it tells you what moved and why.", bullets: ["Spend by team, vendor, category and entity", "Revenue, MRR and customer-health trends", "AI insights without building a single report"] }, agent: { name: "Insight agent", line: "Watches the numbers and surfaces what changed before you ask." }, related: ["accounting", "treasury", "ai-financial-management"] },
  "ai-financial-management": { name: "AI Financial Management", eyebrow: "Intelligence", short: "AI cockpit across modules", headline: "An AI finance team that never clocks out.", sub: "One cockpit pulls every module into a single financial picture. AI agents work inside each one around the clock, so your team owns the decisions and skips the busywork.", capabilities: [{ t: "Financial dashboard", d: "Every module rolled into one live cockpit." }, { t: "Agents in every module", d: "AI working inside cards, payments, close and more." }, { t: "Always on", d: "Reconciles, flags and forecasts around the clock." }], spotlight: { headline: "An AI cockpit for the whole back office.", body: "Every module rolls into one live financial dashboard, with agents working inside each one.", bullets: ["One dashboard across every module", "Agents reconcile, flag and forecast 24/7", "Ask a question, get an answer from your own data"] }, agent: { name: "Finance agents", line: "Work inside every module, 24/7, so your team owns the decisions." }, related: ["reporting", "accounting", "treasury"] },
}

export const productSlugByName: Record<string, string> = {
  "Corporate Cards": "corporate-cards", Expense: "expense", Travel: "travel", Accounts: "accounts", Payments: "payments", Treasury: "treasury", "Stablecoin Ramp": "stablecoin-ramp", Accounting: "accounting", Procurement: "procurement", "Invoicing & Billing": "invoicing-billing", Reporting: "reporting", "AI Financial Management": "ai-financial-management", "AI Finance": "ai-financial-management",
}
